export const SWRKeys = {
  organizations: 'organizations',
  integrations: 'integrations',
  integration: (id: string) => `integration-${id}`,
  organizationStatus: 'organizationStatus',
  githubOrganizations: 'githubOrganizations',
  githubRepositories: 'githubRepositories',
  githubAllRepositories: 'githubAllRepositories',
  githubOrganization: 'githubOrganization',
  servicemapViewData: 'servicemapViewData',
  githubOnboardingStep: 'githubOnboardingStep',
  githubInstallationPR: 'githubInstallationPR',
  githubInstallationLogs: 'githubInstallationLogs',
  vibeKitPreviewEnvironment: 'vibeKitPreviewEnvironment',
  sandboxEnvironment: (chatId: string) => `sandbox-environment-${chatId}`,
  sandboxFiles: (sandboxId: string) => `sandbox-files-${sandboxId}`,
  selectedRepo: (chatId: string) => `selected-repo-${chatId}`,
  sandboxProcesses: (chatId: string) => `sandbox-processes-${chatId}`,
  gitInfo: (folderPath: string) => `git-info-${folderPath}`,
  nextjsProjectInfo: (projectPath: string) => `nextjs-project-info-${projectPath}`,
  screenshot: 'screenshot',
};
